services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: laravel_app
    user: "33:33"
    env_file:
      - .env
    volumes:
      - ./:/var/www
    networks:
      - npm_net
    restart: unless-stopped

  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - npm_net
    restart: unless-stopped

networks:
  npm_net:

volumes:
  dbdata:

